### ISSUE TITLE
how to shut down "INFO:PyEMD"?

### ISSUE THREAD

**Issue by mfly2015** [laszukdawid/PyEMD#10]
how to shut down "INFO:PyEMD"?

INFO:PyEMD.EMD:Standard deviation -- PASSED
INFO:PyEMD.EMD:FINISHED -- RANGE
INFO:PyEMD.EMD:Standard deviation -- PASSED

**Comment by laszukdawid** [comment]
You would have to set logger to the level you wish, i.e. at least one above you don't want to see. The hierarchy is: CRITICAL > ERROR > WARNING > INFO > DEBUG.
So if you don't want to see INFO, but still want to see warnings, errors and critials then set it to WARNING.
Example:
```
from PyEMD import EMD
import logging

emd = EMD()
emd.logger.setLevel(logging.WARNING) # Changes logging to warning level
```

**Comment by laszukdawid** [comment]
Do you find these messages not helpful? Do you use EMD in some pipeline and want to have console clear?
I'm thinking whether these should be hidden by default and your use case could help me decide.

**Comment by mfly2015** [comment]
I use it to deal with financial data. The INFO slows down the computer‘s speed.

**Comment by laszukdawid** [comment]
Ok, I'll consider some more optimizations in following releases. Thanks and hope it helps!
