### ISSUE TITLE
No module named 'PyEMD'

### ISSUE THREAD

**Issue by luispc** [laszukdawid/PyEMD#103]
I have tried to follow the instructions for using PyEMD and I keep receiving the error

       No module named 'PyEMD

when doing

     from PyEMD import EMD

**Comment by nhaduy99** [comment]
I have the same issue!!!

**Comment by shoujiang** [comment]
pip install EMD-signal==1.0.0 
the lastest version has bug!!!

**Comment by shoujiang** [comment]
> I have tried to follow the instructions for using PyEMD and I keep receiving the error
> 
> ```
>    No module named 'PyEMD
> ```
> 
> when doing
> 
> ```
>  from PyEMD import EMD
> ```

try to
pip install EMD-signal==1.0.0

**Comment by laszukdawid** [comment]
Thanks for letting me know. It seems that the latest version (1.1.0) is broken. I'll fix it ASAP.

**Comment by nhaduy99** [comment]
> > I have tried to follow the instructions for using PyEMD and I keep receiving the error
> > ```
> >    No module named 'PyEMD
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when doing
> > ```
> >  from PyEMD import EMD
> > ```
> 
> try to pip install EMD-signal==1.0.0

YEAH, the old version works as a charm, thanks

**Comment by laszukdawid** [comment]
Thanks so much for promptly letting me know! It's fixed now. Installing the latest version should be good. Please try and update if there are any problems.

**Comment by luispc** [comment]
I have just tested the new version and it is working for me. Thank you!!

**Comment by laszukdawid** [comment]
Awesome! Thanks all :)
