### ISSUE TITLE
Idea, Addition of New feature: Statistical Significance test of IMFs

### ISSUE THREAD

**Issue by oshin94** [laszukdawid/PyEMD#104]
@laszukdawid I would like to contribute to this project by adding the test for statistical information content of EMD components.
The test allows one to identify statistically significant IMFs in a noisy data.

The methodology was proposed by Zhaohua Wu, & Huang, N. E. (2004) in their paper, "A study of the characteristics of white noise using the empirical mode decomposition method" and has been established as an effective method to analyse trends especially for hydrological time series.
link: [Original Paper](https://www.jstor.org/stable/4143111)
link: [statistical test for trend identification](https://doi.org/10.1016/j.jhydrol.2013.12.039)

Kindly, let me know if the idea is in line with the aim of this project and if I may raise a PR #PR.

**Comment by laszukdawid** [comment]
Hey @oshin94! Thanks for sharing the idea. Indeed, this would be a nice addition to this package and I'm sure others would like to use it as well :-)

If you are willing to contribute then I'm happy to provide any help that's needed. Is there anything you'd like me to help you with? :-)

Implementation-wise there are two things I want to clarify.
1. You referred to this feature as a *test* and that's likely correct name from methodological / mathematical point of view. However, from code perspective *test* refers to checking that implementation works as expected. We can definitely stay with that name but that will require some additional changes to the code. Again, this isn't a problem but any chance there are other names that might have the same meaning?
2. How do you see the usage of this? What's the input and what's the expected output? Will this be only for EMD's results or more general to any result, like EEMD or CEEMDAN.
3. Regardless of the application, I think it's a good feature on it's own and should be in a separate file. This means that the import would be something like `from PyEMD.tests import whitenoise_check`. What do you think about it? Are there other tests or validations that might be added?

Overall, when adding this feature please consider ease of expansion above the completeness. It's fine to have a slow method with limited use cases but it's important to think how the method connects to the overall.

Really looking forward to help you with this! :-)

**Comment by oshin94** [comment]
Thank you for the response.
1. Regarding the naming convention, I do agree that using terminology such as _test_ may create ambiguity, so it would be better to be more explicit  by using a term like `significancetest`. what do you think?
2.  The significance test can also be used for EEMD as has been done in this [paper](https://doi.org/10.1007/s11517-015-1389-1) and many others. For CEEMDAN, I am currently not aware and would need a little more study but I do not see any reason why it cannot be used for CEEMDAN as well.
Input-Output: It is obvious that the decomposed components will be part of the input, other parameters such as "level of signficance", which IMf to be used for "scaling in a posteriori test" may be set with a default value, which can be overridden if required by the user. Nevertheless, I do agree we need to think this through and I shall make sure to update you on this after a careful examination and implementation of the code. Please do let me know if you have any suggestions.
3. Yes, it would be better to have a separate file for the significance test. The method proposed by Zhaohua Wu, & Huang, N. E. (2004) depends on the white-noise null hypothesis and will not be useful for a time-series contaminated by noise of any other color. One way to solve this would be to establish a statistical significance test scheme against the colored noise of choice.
The same was studied by [Xianyao Chen](https://doi.org/10.1175/JAS-D-12-0213.1) et al. (2013) where they proposed an adaptive method by studying the general characteristics of noise with the aim to identify signals from noisy data without predefinition of the noise in data. I am currently studying this and may be added later on as well.

Regarding my contribution, is there any specific requirement/standard/format that I would need to follow? I did not find any contributing guide, it would be helpful if you can share a little detail so that it becomes easy to reconcile everything together.

**Comment by oshin94** [comment]
Hi @laszukdawid , I have added the separate file for `significancetest` but seeing some code coverage issues #105 . I added some test cases in the test folder, filename: `test_significancetest.py` hoping that the coverage issue will be solved but it still doesn't seem to solve the issue.
Kindly let me know how it may be fixed and if I am missing something as I am not very familiar with code coverage issues.

**Comment by laszukdawid** [comment]
Closing issue; feature added with this PR https://github.com/laszukdawid/PyEMD/pull/105

**Comment by laszukdawid** [comment]
FYI Updated documentation https://pyemd.readthedocs.io/en/latest/check.html
