### ISSUE TITLE
Dear laszukdawid

### ISSUE THREAD

**Issue by HoatranCH** [laszukdawid/PyEMD#107]
**Describe the bug**

**To Reproduce**
Short code showing how to reproduce the issue.

**Expected behavior**

**Screenshots**

**Running environment**
Provide operating system (OS) information, PyEMD version and describe virtual environment (if any).

**Additional context**

**Comment by HoatranCH** [comment]
Dear laszukdawid
I try to import EMD from PyEMD. from PyEMD import EMD, EEMD However, this problem occurs. 
![image](https://user-images.githubusercontent.com/62659390/144762380-4b1605b5-c94a-4e76-a639-db854d5d7ee2.png)
 I try to follow many ways but it does not work. Could you please help me out ?

**Comment by laszukdawid** [comment]
Hey,

In the future, please fill the template that's provided by the issue. It is meant to help you express the error and for me to have all information required to actually answer.

Based on your screenshot I'm guessing that you're using conda to maintain virtual environment. I'm not really sure how installed the PyEMD package but again, based on the provided screenshot, I'm guessing you used anaconda. PyEMD isn't distributed through Anaconda so I don't know how you got it. And, it also seems to be incorrect version as the latest officially released is [1.1.1](https://pypi.org/project/EMD-signal/#history).

I'm sorry but I can't help you here. Your question is about general package management and not specifically to PyEMD.

My suggestions is to uninstall PyEMD (EMD-signal) and use pip to install the official, i.e. `pip install emd-signal`.

**Comment by HoatranCH** [comment]
> Hey,
> 
> In the future, please fill the template that's provided by the issue. It is meant to help you express the error and for me to have all information required to actually answer.
> 
> Based on your screenshot I'm guessing that you're using conda to maintain virtual environment. I'm not really sure how installed the PyEMD package but again, based on the provided screenshot, I'm guessing you used anaconda. PyEMD isn't distributed through Anaconda so I don't know how you got it. And, it also seems to be incorrect version as the latest officially released is [1.1.1](https://pypi.org/project/EMD-signal/#history).
> 
> I'm sorry but I can't help you here. Your question is about general package management and not specifically to PyEMD.
> 
> My suggestions is to uninstall PyEMD (EMD-signal) and use pip to install the official, i.e. `pip install emd-signal`.
It is OK now; the problem is that I pip too many times and make them conflict. My solution: I remove Anacoda and reinstall. Anyway: Thank you laszukdawid for your help.
