### ISSUE TITLE
No module named 'PyEMD'

### ISSUE THREAD

**Issue by fachif** [laszukdawid/PyEMD#108]
**Describe the bug**
I've been trying to run the EMD function in my jupyter notebook but I get the following message: No module named 'PyEMD'.
I don't have the same issue when running in the spyder IDE. The functions that are used in the .ipynb and .py are the same, and the way I import EMD is also the same, following the structure: _from PyEMD import EMD_
Do you have an idea of what could be the issue?

**Comment by laszukdawid** [comment]
You likely didn't install it in your environment. Please google for installing packages in specific environment, especially managing kernals in jupyter notebook.

Sorry, but this isn't related to PyEMD and I've already replied to the same question many many times.

**Comment by DominiqueMakowski** [comment]
I had this issue and scratched my head for some time, until I discovered that it was caused by a conflict with another package.

The solution for me was to run:

`pip uninstall pyemd` first and then reinstall EMD-signal
