### ISSUE TITLE
Support for numpy 1.21?

### ISSUE THREAD

**Issue by bluenote10** [laszukdawid/PyEMD#109]
First of all: Thanks for maintaining this interesting library!

I'm trying to use the library in a context where I have to use numpy 1.21.x. Unfortunately it is currently not possible to use the library specifies a dependency numpy<=1.20.

Would it be possible to support numpy 1.21 as well?

**Comment by laszukdawid** [comment]
Thanks for pointing this. I'll gladly update to be compatible with the newest. I think there was some temporary mismatch between numpy and another library. Let me check if that works now.

**Comment by laszukdawid** [comment]
Source code updated. [Pypi package updated](https://pypi.org/project/EMD-signal/). That's likely all needed.

Thanks again for point this out :) Really appreciated!

**Comment by bluenote10** [comment]
Awesome, thanks for the quick fix!
