### ISSUE TITLE
Add __call__ to class

### ISSUE THREAD

**Issue by lkjell** [laszukdawid/PyEMD#11]
Request to make the classes callable to pass on signal and other parameters.

Example:
```
emd = EMD()
IMF = emd(signal)
```

This can be done by adding 
```
def __call__ (self, S, T=None, max_imf=-1): 
    return self.emd(S,T,max_imf)
```

to the class

**Comment by laszukdawid** [comment]
Thanks for suggestion! :+1: 
This was considered in the past, but for previous shape this was not feasible. You are right that in current form this might be beneficial modification. Let me think on this.

**Comment by laszukdawid** [comment]
Feature added. See commit 12f4cfb84da649ac532fe29800d3bf3dd1fca2bd.
