### ISSUE TITLE
No module named 'PyEMD'

### ISSUE THREAD

**Issue by alexsomoza** [laszukdawid/PyEMD#113]
I saw other past comments about this problem.
I have tried 
pip install EMD-signal==1.0.0
but still continues the problem in jupyter
and after [luispc](https://github.com/luispc) commented [on 2 Nov 2021]}
I tried uninstall and after:
pip install EMD-signal 
with:
from PyEMD import EMD
import numpy as np
s = np.random.random(100)
emd = EMD()
IMFs = emd(s)
_________________________________________________________
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12812/1862948786.py in <module>
----> 1 from PyEMD import EMD
      2 import numpy as np
      3 
      4 s = np.random.random(100)
      5 emd = EMD()

ModuleNotFoundError: No module named 'PyEMD'

Where is the problem ????

Thanks in advance

**Comment by laszukdawid** [comment]
Given that it's in Jupyter my bet is the usual - you're installing it in the wrong environment / kernel.

Please try it in terminal. I've just tested on an empty environment that it works as expected. See logs below.

---

```
kretyn@meland:~$ python -m venv pyemd_venv
kretyn@meland:~$ source pyemd_venv/bin/activate
(pyemd_venv) kretyn@meland:~$ pip install EMD-signal
Collecting EMD-signal
  Downloading EMD_signal-1.2.2-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 741 kB/s 
Collecting scipy>=0.19
  Downloading scipy-1.8.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
     |████████████████████████████████| 41.6 MB 34.8 MB/s 
Collecting pathos>=0.2.1
  Downloading pathos-0.2.8-py2.py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 5.9 MB/s 
Collecting numpy>=1.12
  Using cached numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting multiprocess>=0.70.12
  Downloading multiprocess-0.70.12.2-py38-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 43.5 MB/s 
Collecting pox>=0.3.0
  Downloading pox-0.3.0-py2.py3-none-any.whl (30 kB)
Collecting dill>=0.3.4
  Downloading dill-0.3.4-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 7.9 MB/s 
Collecting ppft>=1.6.6.4
  Downloading ppft-1.6.6.4-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 3.3 MB/s 
Collecting six>=1.7.3
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: numpy, scipy, dill, multiprocess, pox, six, ppft, pathos, EMD-signal
Successfully installed EMD-signal-1.2.2 dill-0.3.4 multiprocess-0.70.12.2 numpy-1.22.2 pathos-0.2.8 pox-0.3.0 ppft-1.6.6.4 scipy-1.8.0 six-1.16.0
(pyemd_venv) kretyn@meland:~$ python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyEMD
>>> from PyEMD import EMD
>>> 
```

**Comment by laszukdawid** [comment]
Given a month without a response I'm assuming it's been either resolved or abandoned. Since I can't reproduce it and I'm going to close the issue as a non-issue.
