### ISSUE TITLE
file setup.py missing

### ISSUE THREAD

**Issue by MaNannn** [laszukdawid/PyEMD#117]
I haven't find setup.py file in this project. Is there any missing there?

**Comment by laszukdawid** [comment]
Can you explain what you are trying to do and why you expect that file?

If you're building the package locally then please update your `pip` and `setuptools` with `pip install --upgrade pip setuptools`. That file, `setup.py`, isn't needed for anything and `setup.cfg` is sufficient (https://setuptools.pypa.io/en/latest/userguide/quickstart.html). In addition, there's a movement towards a single config file `pyproject.toml` so in the "near" future all other files should go away.

**Comment by laszukdawid** [comment]
Please update Python to 3.6 (or higher) and upgrade `pip` and `setuptools` using
```
pip install --upgrade pip setuptools
```
