### ISSUE TITLE
CEEMDAN Extension

### ISSUE THREAD

**Issue by FranzHahn** [laszukdawid/PyEMD#12]
Are there any plans to extend this work to CEEMDAN? I have worked on extending an existing CEEMDAN implementation in Matlab, and would be interested in sharing my knowledge. My python is meh, but I am learning.

**Comment by laszukdawid** [comment]
It wasn't in the plan, but why not ;-) Just send me some corner stone papers on it and I'll try to find some time to implement it. Can't promise on actual delivery time, though.

**Comment by laszukdawid** [comment]
Thanks for patience! Hope this helps :-)
Feel free to ask anything when in doubt.
