### ISSUE TITLE
Problem with seed for reproductibility

### ISSUE THREAD

**Issue by JhonAndersonVelasco** [laszukdawid/PyEMD#124]
Hi
I am trying set a seed for the random numbers generation for make my code reusable, but I got this:

```
CEEMDAN.noise_seed(self,seed=7)
NameError: name 'self' is not defined
```

And when I run it without 'self' I got:

```
CEEMDAN.noise_seed(seed=7)
TypeError: CEEMDAN.noise_seed() missing 1 required positional argument: 'self'
```
And without args names I got:

```
CEEMDAN.noise_seed(7)
TypeError: CEEMDAN.noise_seed() missing 1 required positional argument: 'seed'
```

What should I do for make reproductibility possible?

Thank you

**Comment by laszukdawid** [comment]
Hi @JhonAndersonVelasco ,

You're trying to use `noise_seed` as a static class method which isn't correct. To set the seed you need to first create an instance, e.g.
```python
ceedman = CEEDAN()
ceedman.noise_seed(seed=7)
results = ceedman(signal)
```

Hope this helps

**Comment by JhonAndersonVelasco** [comment]
> Hi @JhonAndersonVelasco ,
> 
> You're trying to use `noise_seed` as a static class method which isn't correct. To set the seed you need to first create an instance, e.g.
> 
> ```python
> ceedman = CEEDAN()
> ceedman.noise_seed(seed=7)
> results = ceedman(signal)
> ```
> 
> Hope this helps

Thank you, I will try it

**Comment by JhonAndersonVelasco** [comment]
It worked really fine, thank you
