### ISSUE TITLE
Where is setup.py

### ISSUE THREAD

**Issue by ManojWarrier** [laszukdawid/PyEMD#127]
Hi. I could not find the setup.py file from the downloaded zip file for installation.

**Comment by shen159876** [comment]
pipi not work and I cannot find the setup.py by using git to install.

**Comment by laszukdawid** [comment]
Hi, it's likely that you haven't updated Python in your system for a while and that you have old version of setuptools. Please execute `pip install --upgrade pip setuptools` to update `pip` and `setuptools`.
`project.toml` is replacing `setup.py`.
