### ISSUE TITLE
QUESTION - Does pyEMD, CEEMDAN try to account for end effects?

### ISSUE THREAD

**Issue by ctanny** [laszukdawid/PyEMD#135]
I am curious to know if there is anything in the package, specifically in the CEEMDAN class that addresses the end effects issues with EMD?
Thanks.

**Comment by laszukdawid** [comment]
Can you please elaborate what do you mean by "end effects issue with EMD?" EMD supports mirroring for time series beginning/end and CEEMDAN uses these algorithms when computing EMD. Is there anything else needed?

**Comment by ctanny** [comment]
I'm not sure. I have been experimenting with regression and LSTM models to help reduce the end effects. But if mirroring reduces these issues and is incorporated into the CEEMDAN algorithm, then thanks! That's a huge potential problem that is dealt with. can you point me to where mirroring is discussed in the docs?
Thank you for sharing this great work.
