### ISSUE TITLE
module object is not callable

### ISSUE THREAD

**Issue by reinforcement-learning-experiments** [laszukdawid/PyEMD#137]
**Describe the bug**

**To Reproduce**
Short code showing how to reproduce the issue.

**Expected behavior**

**Screenshots**

**Running environment**
Provide operating system (OS) information, PyEMD version and describe virtual environment (if any).

**Additional context**

**Comment by reinforcement-learning-experiments** [comment]
![image](https://user-images.githubusercontent.com/63881954/217673824-92b0fe0c-e3a5-4383-a361-c4983ef96577.png)

Anaconda3:
pyemd                     0.5.1           py39h2e25243_1004    conda-forge

IDE: DataSpell 2022.3.2

Error: TypeError: 'module' object is not callable
Please see screenshot

**Comment by ranlychan** [comment]
Because the module "EMD" and the class you were trying to use share the same name. So you could try replace `emd = EMD()` in line 6 with `emd = EMD.EMD()`. It works in my environment.
![image](https://user-images.githubusercontent.com/56482592/217774565-85e89b36-7642-4d9e-b962-03c3ee9867e5.png)

**Comment by reinforcement-learning-experiments** [comment]
@ranlychan you are right. Thanks! This error needs to be changed on the page: https://pyemd.readthedocs.io/en/latest/examples.html
