### ISSUE TITLE
Working with missing data

### ISSUE THREAD

**Issue by devillegaso** [laszukdawid/PyEMD#139]
I am new to EMD and I was wondering if the algorithm would have any problem while working with a time series containing missing data. Until now, I'm removing nans before performing an EMD analysis, but by doing so I'm giving as input a T array of non periodic positions in time. Am I introducing an error? In that case, what would be the correct procedure?

Thanks a lot.

**Comment by laszukdawid** [comment]
Hey, unfortunately missing data is a problem in general. EMD is an empirical method and assumes uniform sampling so you _something_ needs to be present in your time series. There are likely some best practises and suggestions whether and how to interpolate/impute missing data. However, I don't think that's reasonable. EMD is very sensitive to tiny deflections. Maybe other ensemble methods, like EEMD, would be a bit more robust but I don't have knowledge about it.
