### ISSUE TITLE
number of realizations and shifting operations

### ISSUE THREAD

**Issue by Ayubirad** [laszukdawid/PyEMD#144]
Dear @laszukdawid 

In ICEEMDAN options, what are the number of ensemble realizations and shifting operations? in a paper I read recently, it said ICEEMDAN method was used with the following parameters: an ensemble of I = 500 realisations and a total of N = 5000 shifting operations. How can I set these parameters?

is this correct?

```
emd = EMD()
emd.MAX_ITERATION = 5000
ceemdan = CEEMDAN(trials=500, epsilon=0.2, ext_EMD=emd)
```

Best regards,

**Comment by iamnaz1** [comment]
I have same kind of query, EMD uses by default 100 iterations what if I want to limit no. of iterations.
how can I change it ?
