### ISSUE TITLE
how to reconstruct signal after getting IMFs?

### ISSUE THREAD

**Issue by wangwuqi** [laszukdawid/PyEMD#15]
I use CEEMDAN to get IMFs, then how to reconstruct signal?
```
da=raw.get_data()
emd = CEEMDAN()
IMFs = emd(da[0,500:1000])
plt.plot(da[0,500:1000])
plt.show()

plt.plot(IMFs.T)
plt.show()
```
<img width="266" alt="ceemdan" src="https://user-images.githubusercontent.com/22237278/33980483-1bac3996-e0e4-11e7-801e-de9c71670e11.PNG">

**Comment by laszukdawid** [comment]
EMD and so on decompose signal into components. To reconstruct it you just sum up back components. In your case
da = np.sum(IMFs, axis=0)

**Comment by wangwuqi** [comment]
ok,I get it. Thank you
