### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by 0411yab** [laszukdawid/PyEMD#157]
TypeError                                 Traceback (most recent call last)
Cell In[20], line 1
----> 1 eemd_lstm(new_data,i,look_back,data_partition,cap)

File D:\CEEMDAN-EWT-LSTM-main\CEEMDAN-EWT-LSTM-main\myfunctions_france.py:594, in eemd_lstm(new_data, i, look_back, data_partition, cap)
    591 from PyEMD import EEMD
    592 import ewtpy
--> 594 emd = EEMD(noise_width=0.02)
    595 emd.noise_seed(12345)
    597 IMFs = emd(s)

TypeError: 'module' object is not callable

**Comment by 0411yab** [comment]
def eemd_lstm(new_data,i,look_back,data_partition,cap):

    x=i
    data1=new_data.loc[new_data['month'].isin(x)]
    data1=data1.reset_index(drop=True)
    data1=data1.dropna()
    
    datas=data1['LV ActivePower (kW)']
    datas_wind=pd.DataFrame(datas)
    dfs=datas
    s = dfs.values

    from PyEMD import EEMD
    import ewtpy
    
    emd = EEMD(noise_width=0.02)
    emd.noise_seed(12345)

    IMFs = emd(s)

    full_imf=pd.DataFrame(IMFs)
    data_decomp=full_imf.T

**Comment by laszukdawid** [comment]
check other issues or search web
