### ISSUE TITLE
No module named 'PyEMD'

### ISSUE THREAD

**Issue by ZZ646000** [laszukdawid/PyEMD#158]
**Describe the bug**

**To Reproduce**
Short code showinModuleNotFoundError                       Traceback (most recent call last)
Cell In[19], line 1
----> 1 from pyemd import EMD

File ~\anaconda3\Lib\site-packages\pyemd\EMD.py:15
     12 import numpy as np
     13 from scipy.interpolate import interp1d
---> 15 from PyEMD.splines import akima, cubic, cubic_hermite, cubic_spline_3pts, pchip
     16 from PyEMD.utils import get_timeline
     18 FindExtremaOutput = Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]

ModuleNotFoundError: No module named 'PyEMD'
g how to reproduce the issue.

**Expected behavior**

**Screenshots**

**Running environment**
Provide operating system (OS) information, PyEMD version and describe virtual environment (if any).

**Additional context**

**Comment by ZZ646000** [comment]
已解决

**Comment by laszukdawid** [comment]
browse other issues or search web
