### ISSUE TITLE
can_cast() not supported

### ISSUE THREAD

**Issue by zasha18** [laszukdawid/PyEMD#159]
TypeError keeps appearing when running basic tutorial. Tried running emd_tutorial_00_start_01_quicksift.py through both Spyder and Jupyter Notebook with the same result: 

TypeError: can_cast() does not support Python ints, floats, and complex because the result used to depend on the value.
This change was part of adopting NEP 50, we may explicitly allow them again in the future.

**Comment by laszukdawid** [comment]
Can't see how this is relevant to his repo
