### ISSUE TITLE
np_common_type changed

### ISSUE THREAD

**Issue by gems-yc4923** [laszukdawid/PyEMD#160]
**Describe the bug**
AttributeError: `np.find_common_type` was removed in the NumPy 2.0 release. Use `numpy.promote_types` or `numpy.result_type` instead. To achieve semantics for the `scalar_types` argument, use `numpy.result_type` and pass the Python values `0`, `0.0`, or `0j`.

**To Reproduce**
Go to EMD.py, find the `_common_dtype` method and replace it with the following code:
```bash
@staticmethod
def _common_dtype(x: np.ndarray, y: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Casts inputs (x, y) into a common numpy DTYPE."""
    dtype = np.promote_types(x.dtype, y.dtype)
    if x.dtype != dtype:
        x = x.astype(dtype)
    if y.dtype != dtype:
        y = y.astype(dtype)
    return x, y

**Comment by laszukdawid** [comment]
Thanks for letting me know. Updated. Would appreciate confirming.

**Comment by gems-yc4923** [comment]
All good, works well. Thank you for your work
