### ISSUE TITLE
Support for Numpy 2+ in EMD_matlab.py

### ISSUE THREAD

**Issue by LeonardoLancia** [laszukdawid/PyEMD#163]
**Describe the bug**
Same fixes operated on EMD.py should be extended to EMD_matlab.py

**To Reproduce**
Substituting line 432 of EMD_matlab.py with:
dtype = np.find_common_type([x.dtype, y.dtype], [])
should do the job.

**Comment by LeonardoLancia** [comment]
there was a mistake 
the corrected line should be:
dtype = np.promote_types(x.dtype, y.dtype)

**Comment by laszukdawid** [comment]
Thanks for letting me know! Updated in the latest, i.e. `1.6.2` version,

**Comment by LeonardoLancia** [comment]
Thanks for the fix, However, unfortunately now it raises a type error 

File ~\AppData\Local\miniforge-pypy3\envs\modWorks\Lib\site-packages\PyEMD\EMD_matlab.py:433 in _common_dtype
    dtype = deduce_common_type([x.dtype, y.dtype], [])

TypeError: unhashable type: 'list'
