### ISSUE TITLE
TypeError with EMD_matlab

### ISSUE THREAD

**Issue by LeonardoLancia** [laszukdawid/PyEMD#165]
**Describe the bug**
the fix for using numpy>=2 introduces a Type Error when using EMD_matlab:

TypeError: unhashable type: 'list'

**To Reproduce**
from PyEMD import EMD_matlab as EMDm
import numpy as np
x=np.sin(np.linspace(0,24,200))
emdObj = EMDm.EMD()
IMFs=emdObj.emd(x)

**Expected behavior**
no error is expected here

**Running environment**
Windows 10, PyEMD version 1.6.2

**Comment by laszukdawid** [comment]
Thanks for letting me know. It should be fixed now in 1.6.3. Please give it a go, and please let me know if it's actually fixed.

**Comment by LeonardoLancia** [comment]
I tried it and could make it work with two furhter (small) changes:

1) comment line 431:
@staticmethod

2) change line 460 from:

S, T = unify_type(S, T)

to

S, T = unify_types(S, T)

Thank you!

**Comment by laszukdawid** [comment]
Fix added in 1.6.4 (#166 )
