### ISSUE TITLE
 'module' object is not callable, even when I use the example code

### ISSUE THREAD

**Issue by jelmervangestel** [laszukdawid/PyEMD#167]
**Describe the bug**
Type error: 'module' object is not callable, even when I use the example code.

**To Reproduce**
`from PyEMD import EMD
import numpy as np

s = np.random.random(100)
emd = EMD()
IMFs = emd(s)`

**Expected behavior**
I expect the example code to run, but it wont

**Screenshots**
![image](https://github.com/user-attachments/assets/41e26bf7-1618-444e-bab5-6ff7f2c0ec57)

**Running environment**
Windows 11, PyEMD version 1.0.0., anaconda environment using VS Code (Jupyter Notebook).

**Additional context**
I also don't understand if I should use pyemd or PyEMD, and if i need emd or EMD

**Comment by laszukdawid** [comment]
Double check installed the package properly it's meant to be `pip install EMD-signal` (https://pypi.org/project/EMD-signal/). Otherwise, check countless of other similar. I can guarantee that examples work.

**Comment by jelmervangestel** [comment]
![image](https://github.com/user-attachments/assets/5cc911a0-47e0-47f7-831a-95a7d0056c76)

I have installed the module just fine. Looking at other Githubs doesnt get me very far, seeing that the most simple example does not work.

**Comment by laszukdawid** [comment]
You did install a module just fine; but likely not the correct one. Please check others' issues and see if the similar affects you (https://github.com/laszukdawid/PyEMD/issues?q=is%3Aissue+is%3Aclosed).

I just installed pyemd from scratch and used your code as an example.
![image](https://github.com/user-attachments/assets/647d06d1-640e-4526-9c48-4fd7f4a97c12)
