### ISSUE TITLE
The result of EEMD seem changed， why？

### ISSUE THREAD

**Issue by StoneSZG** [laszukdawid/PyEMD#20]
I reinstall my python recently, and download the latest version of PyEMD from GitHub. Then the same code of EEMD get different result, which is a really bad news for my research work. Even the number of IMFs is change.

I don't know what happened, maybe you can give me some advises. Most importantly, is the result of EEMD I got before is wrong?

**Comment by laszukdawid** [comment]
Ensemble empirical mode decomposition (EEMD) performs EMD on an ensemble of original signal augmented with generated noise. Each execution generates different noise, thus the results will change.

In more concrete words, PyEMD does 100 (`EEMD.trials`) iterations where for each iteration a different noise is added to your original signal. The result is an average over all iterations for each IMF. Such algorithm will inherently always give different results.

To make it more reproducible what you can do are:
1. Set manually seed for noise generating system. You can do so with [noise_seed](https://github.com/laszukdawid/PyEMD/blob/master/PyEMD/EEMD.py#L135) method,
```python
eemd = EEMD()
eemd.noise_seed(12345)  # Sets seed=12345, any integer is fine
imfs = eemd(s, t)
```
2. Set a large number of trials, e.g. `eemd = EEMD(trials=10000)`, which should theoretically make the noise in imfs to mutually cancel each other out and making it the 'true' result. Although this, i.e. infinite number of small noise perturbations, is the whole point of EEMD computationally it'll be extremely slow and there isn't any guarantee that it'll ever converge.

**Comment by laszukdawid** [comment]
I'm closing this ticket but feel free to reach out with other questions.
