### ISSUE TITLE
Can't installation PyEMD

### ISSUE THREAD

**Issue by Dizzman** [laszukdawid/PyEMD#21]
~/PyEMD$ **python setup.py install**
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    main()
  File "setup.py", line 9, in main
    from setuptools import setup
**ImportError: No module named setuptools**

Can't install setuptools

**Comment by cvalenzu** [comment]
You tried installing setuptools with pip before using the setup.py?

**Comment by laszukdawid** [comment]
@Dizzman did you try to install `setuptools`?

**Comment by laszukdawid** [comment]
I'll go ahead and close the ticket. If you have any other questions please reach out here or message me directly through email.
