### ISSUE TITLE
Obtain Residual value of last IMF

### ISSUE THREAD

**Issue by nazmibojan** [laszukdawid/PyEMD#24]
Hallo @laszukdawid ,

I just open new issue because this is a different topic. I use EMD to implement _denoising_ to an input signal. To reconstruct a new signal, we have to sum qualified IMFs and residual of EMD process. How can I get the residual value using this library?
Thank you.

Regards,
Nazmi

**Comment by nazmibojan** [comment]
Okay, thank you for the answer, I think that code is very useful.
But, the denoised signal are **sum of qualified IMF** + **Signal Residual**. As we know, the signal residual was the remainder/residual of last sifting process that produce last IMF. Or the last IMF is the residual of sifting process in EMD?
Thank you.

Regards,
Nazmi

*PS: This [paper](https://www.eurasip.org/Proceedings/Eusipco/Eusipco2004/defevent/papers/cr1929.pdf) describes denoising process using EMD.

**Comment by laszukdawid** [comment]
The last row in the array is the residue.

The *noise* is whatever you decide shouldn't be in the signal. Depends on the signal and model that generated it but typically it's the first IMF which is considered the noise. (Not necessarily the only one.) If you want to detrend then also remove residue (or other slow components).

**Comment by nazmibojan** [comment]
Great!
Thank you very much @laszukdawid for this awesome library.
Good luck for you.

Regards,
Nazmi
