### ISSUE TITLE
complex-valued EMD

### ISSUE THREAD

**Issue by WRAR891** [laszukdawid/PyEMD#26]
Hello!

Are any of these EMD variants intended to extract IMF's from complex-valued data? Doesn't seem so by looking at code...

e.g.  https://doi.org/10.1109/LSP.2006.882107

thanks

**Comment by laszukdawid** [comment]
Hey @WRAR891,
Unfortunately non of existing implementations can handle complex values. I'll take a look at the paper and see if it's easy to extend any of current methods.
