### ISSUE TITLE
'EEMD' object has no attribute 'get_imfs_and_residue'

### ISSUE THREAD

**Issue by huangzhaor** [laszukdawid/PyEMD#32]
Can Visualization module help display time series and instantaneous frequencies after 'EEMD' ？

**Comment by laszukdawid** [comment]
I updated (a3dfd12c25ab7a7bd4a1bccfbd724e576fc2b8bc) `Visualisation` examples to show this better.

In general, there's no need for `ge_imfs_and_residue`. What `Visualisation` needs are `imfs` and `residue`. In case of EEMD it's a stretch to call its components IMFs and extracting instantaneous frequency may not have much sense, but unfortunately it is a common thing to do. You can still want to simply see how these component look like.

Check https://github.com/laszukdawid/PyEMD. In short:
```python
import numpy as np
from PyEMD import EEMD, Visualisation

t = np.arange(0, 3, 0.01)
S = np.sin(13*t + 0.2*t**1.4) - np.cos(3*t)

components = EEMD()(S)
imfs, res = components[:-1], components[-1]

vis = Visualisation()
vis.plot_imfs(imfs=imfs, residue=res, t=t, include_residue=True)
# vis.plot_instant_freq(t, imfs=imfs) # 
vis.show()
```

**Comment by huangzhaor** [comment]
Extracting instantaneous frequency is also useful to see whether a single component contains different frequencies.In general,EEMD  algorithm may work out fewer but more accurate frequencies.So could you show me how to find out their  instantaneous frequencyies？

**Comment by laszukdawid** [comment]
It depends, however, how you extract the instantaneous frequency. In case of HHT it's through the Hilbert transform. That transformation doesn't make much sense to be applied against EEMD components since these components often don't have a single instantaneous frequency, nor have zero offset.

If nevertheless you wish to apply Hilbert transform and see "instantaneous frequency" use the example above but uncomment second to last line.

**Comment by huangzhaor** [comment]
Besides, it seems that your EMD algorithm is better than EEMD algorithm. And I don't know what's going wrong.

**Comment by huangzhaor** [comment]
In addition, I change the sampling frequency.

import numpy as np
import math
from PyEMD import EMD, Visualisation

if __name__ == '__main__':
    t = np.arange(0, 0.4, 0.004)
    S = np.sin(400*math.pi*t ) + np.cos(100*math.pi*t)+2
#+ 0.2*t**1.4
    components = EMD()(S)
    print(components )
    imfs, res = components[:-1], components[-1]

    vis = Visualisation()
    vis.plot_imfs(imfs=imfs, residue=res, t=t, include_residue=True)
    vis.plot_instant_freq(t, imfs=imfs) #
    vis.show()

**Comment by huangzhaor** [comment]
Then things went wrong. 

Traceback (most recent call last):
  File "G:/EMD/Pyemd EEMD—— vis.plot_imfs.py", line 15, in <module>
    vis.plot_instant_freq(t, imfs=imfs) #
  File "C:\Users\asus-1\AppData\Roaming\Python\Python36\site-packages\PyEMD\visualisation.py", line 82, in plot_instant_freq
    axes[0].set_title("Instantaneous frequency")
TypeError: 'AxesSubplot' object does not support indexing

**Comment by huangzhaor** [comment]
Yeah！I don't update the code.So how do I update  from the GitHub or through pip in real time ？I just download the cod by the pycharm.

**Comment by KrisLeezz** [comment]
You can download the latest zip. from the GitHub. Uninstall the old one and install the new one.

**Comment by laszukdawid** [comment]
Hey @huangzhaor, apologies for delay in response.

To install from github you can either download as zip (as suggested by @KrisLeezz) or use pip
```
pip install git+https://github.com/laszukdawid/PyEMD
```

The official release version, i.e. `EMD-signal` is unfortunately lagging behind. The main reason is that I don't want to push too often but that isn't a valid reason. Will try to do more often.
