### ISSUE TITLE
Example for visualization module has a little spelling mistakes

### ISSUE THREAD

**Issue by huangzhaor** [laszukdawid/PyEMD#33]
import numpy as np
from PyEMD import EMD, Visualisation

t = np.arange(0, 3, 0.01)
S = np.sin(13*t + 0.2*t**1.4) - np.cos(3*t)

emd = EMD()
emd.emd(S)
imfs, res = emd.get_imfs_and_residue()

vis = Visulisation(emd) #Visulisation lose  'a'
vis.plot_imfs()
vis.plot_instant_freq(t)
vis.show()

**Comment by laszukdawid** [comment]
Ay, missed it. Thanks!
