### ISSUE TITLE
Getting the emd value of a *.wav file

### ISSUE THREAD

**Issue by zchyobtinario** [laszukdawid/PyEMD#37]
I tried getting the emd of a *.wav file using this code `sample_rate, signal = scipy.io.wavfile.read('7b0e160e-0505-459e-8ecb-304d7afae9d2-1437446210164-1.7-m-04-dk.wav')
emd = EMD()
emd.emd(signal)
imfs, res = emd.get_imfs_and_residue()`

It output an error like this
Traceback (most recent call last):
  File "C:/Users/user2/PycharmProjects/BB/EMD-signal.py", line 28, in <module>
    emd.emd(signal1)
  File "C:\Users\user2\BB\lib\site-packages\PyEMD\EMD.py", line 788, in emd
    max_env, min_env, eMax, eMin = self.extract_max_min_spline(T, imf)
  File "C:\Users\user2\BB\lib\site-packages\PyEMD\EMD.py", line 138, in extract_max_min_spline
    pp_res = self.prepare_points(T, S, max_pos, max_val, min_pos, min_val)
  File "C:\Users\user2\BB\lib\site-packages\PyEMD\EMD.py", line 177, in prepare_points
    return self._prepare_points_simple(T, S, max_pos, max_val, min_pos, min_val)
  File "C:\Users\user2\BB\lib\site-packages\PyEMD\EMD.py", line 319, in _prepare_points_simple
    if ind_max[0] < ind_min[0]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by KrisLeezz** [comment]
There maybe something wrong with your input data. You should transform the data into the format supported by this program.

**Comment by laszukdawid** [comment]
Hey @zchyobtinario, sorry for delay in replying.

The error means that you're comparing lists whereas at this point it's expecting a single value (first extrama). I'm guessing that your wav file contains stereo sound, i.e. at least two channels. This won't work as multivariate EMD is not yet available.

I'd suggest performing a single channel analysis or converting these to a mono.

If you'd like to work together on this feel free to reach out and share the file.
