### ISSUE TITLE
statistical signiﬁcance of IMF

### ISSUE THREAD

**Issue by KrisLeezz** [laszukdawid/PyEMD#38]
Maybe there is no functions to carry out statistical signiﬁcance of IMF.

**Comment by KrisLeezz** [comment]
This the link of Matlab source code of EEMD and significance test and etc.. The author is Z.H. WU. They were collected and modified by S.C. SUN.
[https://github.com/KrisLeezz/practice/tree/master/Matlab%20runcode](url)
I rewrite the significance test part into python. This is the link: [https://github.com/KrisLeezz/practice/tree/master/significanceIMF](url)
This is the reference paper: [https://royalsocietypublishing.org/doi/abs/10.1098/rspa.2003.1221](url)
There are some questions in the source codes, such as the transformation coefficient and equation 3.4. I suspect there was a mistake, but I am not sure. I hope someone interested in them can help me.

**Comment by laszukdawid** [comment]
Hey @KrisLeezz, thanks for sharing your finding on the significance test on white noise using EMD.

I hate to do this, however, this finding isn't related to the PyEMD code. I'm closing this topic on the basis that there isn't anything to do with it. However, feel free to reopen it if you have any suggestion related to the PyEMD improvement.
