### ISSUE TITLE
Power Spectra add on

### ISSUE THREAD

**Issue by sonamghosh** [laszukdawid/PyEMD#41]
Since a lot of papers that use EMD showcase power spectrum plots. I was wondering if you could add one in the visualization.py file?

**Comment by laszukdawid** [comment]
Sure. Can you just send me a specific paper what exactly you have in mind?

**Comment by sonamghosh** [comment]
https://ieeexplore.ieee.org/document/6892169 I believe this is one of them. I can link a couple more if you want

**Comment by MarcMukendiMpanda** [comment]
Can someone has the code to compute the singularity spectrum
