### ISSUE TITLE
Option to obtain upper and lower envelope of the first IMF from EMD

### ISSUE THREAD

**Issue by bs2019** [laszukdawid/PyEMD#48]
Hello!

Maybe, there is an option to obtain upper and lower envelope of the first IMF from EMD ? I need this to graph and explain the process in a particular application. I really thank you help.

**Comment by laszukdawid** [comment]
Hi, apologies for the delay!

I'm not sure if I understand what you want. Are these envelopes (bottom and top) of a produced IMF, or you want proto-IMF, i.e. after each sifting iteration?

In the latter case, there isn't currently such functionality and I'm hesitant to add it.

Getting envelope of already created IMF is the same as obtaining an envelope of any signal. A way to do it, but that's definitely not an only way, is to use Hilbert Transformation. To do so in Python you can use [one of my scripts](https://github.com/laszukdawid/signal-helpers/blob/master/hilbert_transform.py) where you'll have to replace `signal` (lines 13-14) with the result of EMD, e.g.

```python
IMFs = EMD(s)
signal = IMFs[0]
```
