### ISSUE TITLE
numpy deprecation warning

### ISSUE THREAD

**Issue by mpearmain** [laszukdawid/PyEMD#56]
Not an Error but with with the following numpy version (`numpy==1.16.4`) running CEEMDAN returns a deprecation warning:

`/home/mpearmain/venv/python3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead`

**Comment by laszukdawid** [comment]
Thanks for highlighting this. I'll fix this in few days.

Dawid

**Comment by mpearmain** [comment]
sorry, i was too hasty... the problem arises from using pandas and passing a series not `numpy`
