### ISSUE TITLE
wrong calculation of instant frequency in visualisation.py

### ISSUE THREAD

**Issue by newusername** [laszukdawid/PyEMD#58]
https://github.com/laszukdawid/PyEMD/blob/c285242ecfd59c33f163f89d2af00c600d66421c/PyEMD/visualisation.py#L112

should be:
`return np.diff(inst_phase)/(2*np.pi*(t[1]-t[0])) `
as was correctly done in hht_example.py

**Comment by laszukdawid** [comment]
Thanks @newusername for spotting this. Fixed.
