### ISSUE TITLE
BEMD Memory Error

### ISSUE THREAD

**Issue by gouzmi** [laszukdawid/PyEMD#60]
Hello Dawid !  

First of all, thank you so much for all your work i really appreciate your library.

I know that bidimensional EMD ( BEMD.BEMD() ) stills in developpement and that's why i would like to notify you about this memory error which happens when i want to decompose my image (code below)

I also tried to decompose with EMD2d.EMD2D() and it worked. However it only returned two images ( i think it's the image minus the residue, and the residue) and i really need to return all of the IMFs.

computer : Ubuntu 18.10, Intel i9, 64go RAM and RTX 24go

kind regards,
Guillaume

### Here's my code :

`import numpy as np
import cv2
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os, sys
import math
import datetime
from skimage import measure
import datetime
from PyEMD import BEMD

print(datetime.datetime.now())
bemd = BEMD.BEMD()  

IMG_SIZE = 700
img1 = cv2.imread('/media/thesard/DATA/Guillaume/Recherche DMLA/DMLA-TimeLapse-Project/DMLA-TimeLapse-Align renamed/000_AB_J/IR OD/aligned_0_20151118_mapped.png')
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img1 = cv2.resize(img1, (IMG_SIZE, IMG_SIZE))
IMFs_2D = bemd(img1)

print(datetime.datetime.now())`

### And the error :

`
MemoryError                               Traceback (most recent call last)
<ipython-input-3-eb9ecc85c56e> in <module>
     13 # IMFs_2D = emd2d(img1)
     14 # plt.imshow(IMFs_2D[0],cmap='gray')
---> 15 IMFs_2D = bemd(img1)
     16 
     17 print(datetime.datetime.now())

~/anaconda3/envs/DMLA-Env/lib/python3.6/site-packages/EMD_signal-0.2.7-py3.6.egg/PyEMD/BEMD.py in __call__(self, image, max_imf)
     54 
     55     def __call__(self, image, max_imf=-1):
---> 56         return self.bemd(image, max_imf=max_imf)
     57 
     58     def extract_max_min_spline(self, image, min_peaks_pos, max_peaks_pos):

~/anaconda3/envs/DMLA-Env/lib/python3.6/site-packages/EMD_signal-0.2.7-py3.6.egg/PyEMD/BEMD.py in bemd(self, image, max_imf)
    226                 self.logger.debug("min_peaks_pos = %i  |  max_peaks_pos = %i", len(min_peaks_pos[0]), len(max_peaks_pos[0]))
    227                 if len(min_peaks_pos[0])>1 and len(max_peaks_pos[0])>1:
--> 228                     min_env, max_env = self.extract_max_min_spline(imf, min_peaks_pos, max_peaks_pos)
    229                     mean_env = 0.5*(min_env+max_env)
    230 

~/anaconda3/envs/DMLA-Env/lib/python3.6/site-packages/EMD_signal-0.2.7-py3.6.egg/PyEMD/BEMD.py in extract_max_min_spline(self, image, min_peaks_pos, max_peaks_pos)
     73         min_val = np.array([image[x,y] for x, y in zip(*min_peaks_pos)])
     74         max_val = np.array([image[x,y] for x, y in zip(*max_peaks_pos)])
---> 75         min_env = self.spline_points(min_peaks_pos[0], min_peaks_pos[1], min_val, xi, yi)
     76         max_env = self.spline_points(max_peaks_pos[0], max_peaks_pos[1], max_val, xi, yi)
     77         return min_env, max_env

~/anaconda3/envs/DMLA-Env/lib/python3.6/site-packages/EMD_signal-0.2.7-py3.6.egg/PyEMD/BEMD.py in spline_points(cls, X, Y, Z, xi, yi)
     84         Griddata algorithm didn't work.
     85         """
---> 86         spline = Rbf(X, Y, Z, function='cubic')
     87         return spline(xi, yi)
     88 

~/.local/lib/python3.6/site-packages/scipy/interpolate/rbf.py in __init__(self, *args, **kwargs)
    239             setattr(self, item, value)
    240 
--> 241         self.nodes = linalg.solve(self.A, self.di)
    242 
    243     @property

~/.local/lib/python3.6/site-packages/scipy/interpolate/rbf.py in A(self)
    245         # this only exists for backwards compatibility: self.A was available
    246         # and, at least technically, public.
--> 247         r = squareform(pdist(self.xi.T, self.norm))  # Pairwise norm
    248         return self._init_function(r) - np.eye(self.N)*self.smooth
    249 

~/.local/lib/python3.6/site-packages/scipy/spatial/distance.py in squareform(X, force, checks)
   2176 
   2177         # Allocate memory for the distance matrix.
-> 2178         M = np.zeros((d, d), dtype=X.dtype)
   2179 
   2180         # Since the C code does not support striding using strides.

MemoryError: Unable to allocate array with shape (93929, 93929) and data type float64
`

**Comment by laszukdawid** [comment]
Hi @gouzmi 

Unfortunately that's expected. As the error states, you are trying to allocate a large space in memory - 93929 x 93929 float64 which is around 564650050624 bits which is around 66 gigabytes. Current implementation of EMD2D and BEMD does not support large images which is why I don't want to support these two.

Sorry for the inconvenience and feel free to update code accordingly. Any improvement is welcome :-)

Thanks,
Dawid
