### ISSUE TITLE
version

### ISSUE THREAD

**Issue by shenjianaixuexi** [laszukdawid/PyEMD#64]
is  there any version for python2.7?

**Comment by laszukdawid** [comment]
It's the same version; it works on Python2.7.

Python2.7 is being deprecated so PyEMD will soon drop support for it.

**Comment by shenjianaixuexi** [comment]
Thank for&nbsp; you&nbsp;so much !&nbsp; 
 Python 2.7&nbsp; is&nbsp;indeed avalible .&nbsp; But&nbsp; someone who&nbsp; wants to use it ,must install&nbsp;&nbsp; Sphinx==1.6.5&nbsp; first . 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dawid Laszuk"<notifications@github.com&gt;; 
发送时间: 2019年12月22日(星期天) 下午4:30
收件人: "laszukdawid/PyEMD"<PyEMD@noreply.github.com&gt;; 
抄送: "jianji"<457037482@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [laszukdawid/PyEMD] version (#64)




It's the same version; it works on Python2.7.
 
Python2.7 is being deprecated so PyEMD will soon drop support for it.
