### ISSUE TITLE
The first IMF is [0,0,0....] all zero when set "parallel=False" using CEEMDAN or EEMD

### ISSUE THREAD

**Issue by muqingCai** [laszukdawid/PyEMD#65]
I used the CEEDMAN like this
`  ceemdan = CEEMDAN(parallel=False)
    ceemdan.trials = 10
    max_IMF = 5
    eIMFs = ceemdan.ceemdan(ts, max_imf=5)`
But get the result as  
[[ 0.          0.          0.         ...  0.          0.,   0.        ], [ 5.0205319   5.05441522 -4.62335232 ...  0.39283641 -6.48358469,  -1.91464419], [ 3.3244119   3.34833722 -3.15371022 ...  0.73033395  7.22461791,  11.2976024 ], [ 1.61699314  1.6286....]

and when I set 'parallel=False', the result is true, the results are as follows:
[[  4.9391269    4.92000825  -4.62921163 ...   0.48549634  -6.37283759,   -1.79111796], [  3.60359462   3.61213567  -3.38193192 ...   1.11980536   6.91068809,   10.10722885], [  1.32640539   1.34183321  -0.45469606 ...  14.26556025  17.83044674,   20.64068

I have used the latest code,  the problem of "too many files" would be happened when used parallel=True, how can I get the true results when I use 'parallel=False'

**Comment by muqingCai** [comment]
@laszukdawid Can you solve it for me, thank you very much～～～

**Comment by laszukdawid** [comment]
Hi, unfortunately I'm a bit busy now. Most likely I won't look into this until the new year.

**Comment by muqingCai** [comment]
> Hi, unfortunately I'm a bit busy now. Most likely I won't look into this until the new year.
> […](#)
Do you think it's a bug or something wrong, my work has been blocked because of that.
It's so sorry to bother you~~~

**Comment by laszukdawid** [comment]
I just read your first comment again and I'm not sure what's the configuration difference between both runs.

If you're getting an IMF consistently with all zeros, then that's a bug. However, it's more likely a bug in returning IMFs rather than with the algorithm. Please notice that your second IMF from the set with zero-IMF is quite similar (up to noise) to the first IMF in the set without zero-IMF. This suggests that you should be fine with simply ignoring the zero-IMF (and reordering the rest).

It'd be interesting to see if it's possible to reproduce the results. Would you mind sending me the data to pyemd@dawid.lasz.uk?

**Comment by muqingCai** [comment]
Thx so much, it’s very nice of you. The data is as shown in the attachment. I think that ingoring the first IMF could get the right results but what the first imf all zero???



蔡木庆
华南理工大学
2013级计算机科学与工程学院

电话：18819451535
邮箱： &nbsp;1398384979@qq.com




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dawid Laszuk"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 中午1:51
收件人:&nbsp;"laszukdawid/PyEMD"<PyEMD@noreply.github.com&gt;;
抄送:&nbsp;"蔡木庆"<1398384979@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [laszukdawid/PyEMD] The first IMF is [0,0,0....] all zero when set "parallel=False" using CEEMDAN or EEMD (#65)




I just read your first comment again and I'm not sure what's the configuration difference between both runs.
 
If you're getting an IMF consistently with all zeros, then that's a bug. However, it's more likely a bug in returning IMFs rather than with the algorithm. Please notice that your second IMF from the set with zero-IMF is quite similar (up to noise) to the first IMF in the set without zero-IMF. This suggests that you should be fine with simply ignoring the zero-IMF (and reordering the rest).
 
It'd be interesting to see if it's possible to reproduce the results. Would you mind sending me the data to pyemd@dawid.lasz.uk?

**Comment by muqingCai** [comment]
Thx so much, it’s very nice of you. The data is as shown in the attachment. I think that ingoring the first IMF could get the right results but what the first imf all zero???



蔡木庆
华南理工大学
2013级计算机科学与工程学院

电话：18819451535
邮箱： &nbsp;1398384979@qq.com




&nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"Dawid Laszuk"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 中午1:51
收件人:&nbsp;"laszukdawid/PyEMD"<PyEMD@noreply.github.com&gt;;
抄送:&nbsp;"蔡木庆"<1398384979@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [laszukdawid/PyEMD] The first IMF is [0,0,0....] all zero when set "parallel=False" using CEEMDAN or EEMD (#65)




I just read your first comment again and I'm not sure what's the configuration difference between both runs.
 
If you're getting an IMF consistently with all zeros, then that's a bug. However, it's more likely a bug in returning IMFs rather than with the algorithm. Please notice that your second IMF from the set with zero-IMF is quite similar (up to noise) to the first IMF in the set without zero-IMF. This suggests that you should be fine with simply ignoring the zero-IMF (and reordering the rest).
 
It'd be interesting to see if it's possible to reproduce the results. Would you mind sending me the data to pyemd@dawid.lasz.uk?
