### ISSUE TITLE
EEMD speed up

### ISSUE THREAD

**Issue by StianIsmar** [laszukdawid/PyEMD#77]
When running EEMD with one signals consisting of 20.000 samples, it takes around 1.2 minutes to run the function underneath. Is there anything that can be done to speed it up? I need to run 400 of these signal so it takes some time.
```python
from PyEMD import EEMD
import numpy as np
import matplotlib.pyplot as plt

def eemd(wt_name, interval_num, component,signal,timestamps,plotting=False):

	# Define signal
	S = signal
	t = timestamps

	# Assign EEMD to `eemd` variable
	eemd = EEMD()
	# Say we want detect extrema using parabolic method
	emd = eemd.EMD
	emd.extrema_detection="parabol"
	# Execute EEMD on S
	eIMFs = eemd.eemd(S, t)
	nIMFs = eIMFs.shape[0]
	# Plot results	

	if plotting:
		# plt.plot(t, S, 'r')
		# plt.title("Filtered signal")

		
		f, axs = plt.subplots((nIMFs)+1,1,figsize=(15,20))

		# plotting the filtered signal first
		axs[0].plot(t, S, 'r')
		plt.title("{component} filtered signal from {wt_name}. \n Interval number {interval_num}.")
		for n in range(nIMFs):
		    axs[n+1].plot(t, eIMFs[n], 'g')
		    plt.ylabel("eIMF %i" %(n+1))
		    plt.locator_params(axis='y', nbins=5)
		    plt.xlabel("Time [s]")
		    plt.tight_layout()
		    plt.savefig(f' for {wt_name}', dpi=120)
		plt.show()

		print(f'{eIMFs.shape} is the shape of the IMFs!')

	eIMFs = np.insert(eIMFs,0,S,axis=0) # Inserting the original signal into the fist index of the returned array
	print(f'{eIMFs.shape} is the shape of the IMFs!')
	return eIMFs
```
After running it I am just interested in the first intrinsic mode.

**Comment by laszukdawid** [comment]
Unfortunately, CEEMDAN and EEMD will take a while to produce results. In their core, they perform many EMD evaluations on a signal with added noise. I haven't done many experiments recently but it does make sense that it'd take more than a minute on large/complex signals.

In case when you're only interested in the first component you can pass `max_imf=1` on the intiation which will halt exeuction of more components than first. Remember though that in return you'll have two components, i.e. the first one and the residue being (signal without the first component).

This would be something like
```python
from PyEMD import CEEMDAN

s = generate_signal()

ceemdan = CEEMDAN()
results = ceemdan(s, max_imf=1)
assert results.shape[0] == 2
```

Hope this helps.

**Comment by laszukdawid** [comment]
Additionally, I've added a F.A.Q. section to the readme to address your question. Feel free to check it out.

**Comment by StianIsmar** [comment]
Thank you!
