### ISSUE TITLE
2DEMD

### ISSUE THREAD

**Issue by akshay-vaidya** [laszukdawid/PyEMD#8]
Can I use this module for computing IMFs of images?

**Comment by laszukdawid** [comment]
Not in current version, but I'm just finishing few things and should release within a week.

**Comment by laszukdawid** [comment]
@akshay-vaidya Image decomposition support added. It uses 2D extrema definitions based on maximum filter. For me it was slightly not intuitive initially, but then it made sense. If you have any comments fee free to write them :)

**Comment by akshay-vaidya** [comment]
@laszukdawid Thats great! I will start working on it.
