### ISSUE TITLE
CEEMD Parameters different from paper

### ISSUE THREAD

**Issue by Jogima-cyber** [laszukdawid/PyEMD#80]
Hello there, I'm trying to implement a paper in python, which uses CEEMD. I didn't know this method until I read it. My problem is that the paper specifies following parameters : 
<img width="522" alt="Capture d’écran 2020-07-15 à 15 12 52" src="https://user-images.githubusercontent.com/58483181/87549371-047afe80-c6ae-11ea-937a-87f150a052a8.png">
But I don't find any similar parameters in PyEMD. Do you know how to implement those parameters with CEEMDAN class of PyEMD ?
Thanks in advance.

**Comment by laszukdawid** [comment]
Hi, you can specify `max_imfs` on every instance run, for example here https://github.com/laszukdawid/PyEMD/blob/master/PyEMD/CEEMDAN.py#L171. Same for the noise scale which is provided on instantiating the CEEMDAN class (code doc https://github.com/laszukdawid/PyEMD/blob/master/PyEMD/CEEMDAN.py#L60-L67). Feel free to take a look at the documentation https://pyemd.readthedocs.io/en/latest/ceemdan.html.

Regarding max iterations that's defined on the EMD. If you want to modify it then I'd suggest you create your own EMD first and then pass it to the CEEMDAN.

```python
from PyEMD import EMD, CEEMDAN
emd = EMD()
emd.MAX_ITERATION = 10000
ceemdan = CEEMDAN(epsilon=... ,ext_EMD=emd)
```
