### ISSUE TITLE
NA-MEMD

### ISSUE THREAD

**Issue by zeydabadi** [laszukdawid/PyEMD#91]
Is the NA-MEMD method described in "Rehman N, Park C, Huang NE, et al. EMD via MEMD: multivariate noise-aided computation of standard EMD. Adv  Adapt Data Anal. 2013;5(02):1350007. " has been implemented in this package? If not, what method is the closest to the NA-MEMD?

**Comment by laszukdawid** [comment]
No and I don't know.
