### ISSUE TITLE
CEEMDAN

### ISSUE THREAD

**Issue by SChandel-cmd** [laszukdawid/PyEMD#94]
I was trying to use the CEEMDAN method on a signal but it goes on for around 30 minutes and gives me something like "dydx value needs to be finite". Is there any CEEMDAN usage example I could refer to?

**Comment by laszukdawid** [comment]
Yes. Please scroll down on https://github.com/laszukdawid/PyEMD

**Comment by SChandel-cmd** [comment]
Just checked that is the method which I was using and it's still taking a really long time whereas on matlab there exists a module which is able to do this under a minute.
Using PyEMD- EMD takes around 2 minutes, EEMD around 17, and CEEMDAN goes on for an hour+ and does not stop.
Could this be due to the density of the signal I'm processing?
I did normalize the array before parsing it

> Yes. Please scroll down on https://github.com/laszukdawid/PyEMD
